name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if tag exists
        run: |
          if git rev-parse "${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "❌ Tag ${{ github.event.inputs.version }} already exists. Exiting."
            exit 1
          fi

      - name: Setup Node.js and enable pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Create Git tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist
          git commit -m "Include dist directory for release" || echo "No changes to commit"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
          git reset --soft HEAD~1  # Undo commit but keep changes staged

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: "Automated release of ${{ github.event.inputs.version }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
