name: 📦 Deploy Storybook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Prepare built files to deployment
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install OpenVPN
        run: | 
          sudo apt update 
          sudo apt install -y openvpn openvpn-systemd-resolved
      
      - name: Reconstruct ovpn file from secrets
        run: |
            echo "${{ secrets.SYSNOVE_OVPN }}" > sysnove.ovpn

      - name: Get built files
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: "./sysnove.ovpn"

      - name: Clean server directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.SYSNOVE_HOST }}
          username: ${{ secrets.SYSNOVE_USER }}
          password: ${{ secrets.SYSNOVE_PASSWORD }}
          script: rm -rf ${{ vars.SYSNOVE_PROJECT_DIR }}/*
      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SYSNOVE_HOST }}
          username: ${{ secrets.SYSNOVE_USER }}
          password: ${{ secrets.SYSNOVE_PASSWORD }}
          source: "./storybook-static/*"
          target: ${{ vars.SYSNOVE_PROJECT_DIR }}
          strip_components: 1 # do not create the dist folder in target
